// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SortResourceVS2022
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSortResourceVS2022PackageString = "e66c954e-2807-4d35-914d-ec105fa3d71d";
        public static Guid guidSortResourceVS2022Package = new Guid(guidSortResourceVS2022PackageString);

        public const string guidUIContextString = "c3af2fa7-b17e-43f3-ba08-6cb2aa4426c2";
        public static Guid guidUIContext = new Guid(guidUIContextString);

        public const string guidSortResourceVS2022PackageCmdSetString = "375e429d-4fb9-420b-9ad5-bb17130e256b";
        public static Guid guidSortResourceVS2022PackageCmdSet = new Guid(guidSortResourceVS2022PackageCmdSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SortResourceCommandId = 0x0100;
    }
}